spring:
  application:
    name: dusharding
  sharding:
    datasources:
      ds0:
        url: jdbc:mysql://127.0.0.1:3306/db0?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: 123456
      ds1:
        url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: 123456
    tables:
      user:
        actualDataNodes: ds0.user0, ds0.user1, ds0.user2, ds1.user0, ds1.user1, ds1.user2
        databaseStrategy:
          shardingColumn: id
          algorithmExpression: ds${id % 2}
        tableStrategy:
          shardingColumn: id
          algorithmExpression: user${id % 3}

      t_order:
        actualDataNodes: ds0.t_order0, ds0.t_order1, ds1.t_order0, ds1.t_order1
        databaseStrategy:
          shardingColumn: uid
          algorithmExpression: ds${uid % 2}
        tableStrategy:
          shardingColumn: id
          algorithmExpression: t_order${id % 2}